[project]
name = "nextupcv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Satyam Vishwakarma", email = "officialsatyamvishwakarma06@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.141.1",
    "pdfplumber>=0.11.10",
    "python-multipart>=0.0.32",
    "scikit-learn>=1.9.0",
    "spacy>=3.8.14",
    "uvicorn>=0.52.1",
]

[project.scripts]
NextUpCV = "NextUpCV:main"

[tool.uv]
package = false