[project]
name = "nextupcv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Satyam Vishwakarma", email = "officialsatyamvishwakarma06@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "en-core-web-sm",
    "fastapi>=0.141.1",
    "pdfplumber>=0.11.10",
    "python-multipart>=0.0.32",
    "scikit-learn>=1.9.0",
    "spacy>=3.8.14",
    "streamlit>=1.61.1",
    "uvicorn>=0.52.1",
]

[project.scripts]
NextUpCV = "NextUpCV:main"

[tool.uv]
package = false

[tool.uv.sources]
en-core-web-sm = { url = "https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0.tar.gz" }
